---
name: CI
on: push
jobs:
  build-clang-concepts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: 'true'
      - uses: docker://lucteo/action-cxx-toolkit.clang12:latest
        with:
          cc: clang-12
          checks: build warnings
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit.main:latest
        with:
          checks: clang-format
          clangformatdirs: src
